name: ordem_siai
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  provider: ^6.0.4
  intl: ^0.17.0
  location: ^4.4.0
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  flutter_feather_icons: ^2.0.0+1
  flutter_native_timezone: ^2.0.0
  auto_size_text: ^3.0.0
  easy_mask: ^2.0.1
  jwt_decoder: ^2.0.1
  package_info_plus: ^3.0.2
  easy_sidemenu: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
